apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookcatalog-deployment
  labels:
    app: bookcatalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookcatalog
  template:
    metadata:
      labels:
        app: bookcatalog
    spec:
      containers:
        - name: bookcatalog
          image: docker.io/your-dockerhub-username/bookcatalog:latest
          ports:
            - containerPort: 8080
